/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.BusinessRegistrationNumberMask;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessRegistrationNumber
 */
public class BusinessRegistrationNumberTest {
    private final BusinessRegistrationNumber model = new BusinessRegistrationNumber();

    /**
     * Model tests for BusinessRegistrationNumber
     */
    @Test
    public void testBusinessRegistrationNumber() {
        // TODO: test BusinessRegistrationNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'jurisdiction'
     */
    @Test
    public void jurisdictionTest() {
        // TODO: test jurisdiction
    }

    /**
     * Test the property 'supported'
     */
    @Test
    public void supportedTest() {
        // TODO: test supported
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'masks'
     */
    @Test
    public void masksTest() {
        // TODO: test masks
    }

}
