/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.PersonOfSignificantControl;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Business
 */
public class BusinessTest {
    private final Business model = new Business();

    /**
     * Model tests for Business
     */
    @Test
    public void testBusiness() {
        // TODO: test Business
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'tradestyleName'
     */
    @Test
    public void tradestyleNameTest() {
        // TODO: test tradestyleName
    }

    /**
     * Test the property 'taxIDNumber'
     */
    @Test
    public void taxIDNumberTest() {
        // TODO: test taxIDNumber
    }

    /**
     * Test the property 'businessRegistrationNumber'
     */
    @Test
    public void businessRegistrationNumberTest() {
        // TODO: test businessRegistrationNumber
    }

    /**
     * Test the property 'dayOfIncorporation'
     */
    @Test
    public void dayOfIncorporationTest() {
        // TODO: test dayOfIncorporation
    }

    /**
     * Test the property 'monthOfIncorporation'
     */
    @Test
    public void monthOfIncorporationTest() {
        // TODO: test monthOfIncorporation
    }

    /**
     * Test the property 'yearOfIncorporation'
     */
    @Test
    public void yearOfIncorporationTest() {
        // TODO: test yearOfIncorporation
    }

    /**
     * Test the property 'jurisdictionOfIncorporation'
     */
    @Test
    public void jurisdictionOfIncorporationTest() {
        // TODO: test jurisdictionOfIncorporation
    }

    /**
     * Test the property 'shareholderListDocument'
     */
    @Test
    public void shareholderListDocumentTest() {
        // TODO: test shareholderListDocument
    }

    /**
     * Test the property 'financialInformationDocument'
     */
    @Test
    public void financialInformationDocumentTest() {
        // TODO: test financialInformationDocument
    }

    /**
     * Test the property 'dunsNumber'
     */
    @Test
    public void dunsNumberTest() {
        // TODO: test dunsNumber
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'peopleOfSignificantControl'
     */
    @Test
    public void peopleOfSignificantControlTest() {
        // TODO: test peopleOfSignificantControl
    }

    /**
     * Test the property 'filings'
     */
    @Test
    public void filingsTest() {
        // TODO: test filings
    }

    /**
     * Test the property 'articleOfAssociation'
     */
    @Test
    public void articleOfAssociationTest() {
        // TODO: test articleOfAssociation
    }

    /**
     * Test the property 'registrationDetails'
     */
    @Test
    public void registrationDetailsTest() {
        // TODO: test registrationDetails
    }

    /**
     * Test the property 'annualReport'
     */
    @Test
    public void annualReportTest() {
        // TODO: test annualReport
    }

}
