/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.Location;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessSearchRequestBusinessSearchModel
 */
public class BusinessSearchRequestBusinessSearchModelTest {
    private final BusinessSearchRequestBusinessSearchModel model = new BusinessSearchRequestBusinessSearchModel();

    /**
     * Model tests for BusinessSearchRequestBusinessSearchModel
     */
    @Test
    public void testBusinessSearchRequestBusinessSearchModel() {
        // TODO: test BusinessSearchRequestBusinessSearchModel
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'jurisdictionOfIncorporation'
     */
    @Test
    public void jurisdictionOfIncorporationTest() {
        // TODO: test jurisdictionOfIncorporation
    }

    /**
     * Test the property 'dunsNumber'
     */
    @Test
    public void dunsNumberTest() {
        // TODO: test dunsNumber
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

}
