/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessRegistrationNumberMask
 */
public class BusinessRegistrationNumberMaskTest {
    private final BusinessRegistrationNumberMask model = new BusinessRegistrationNumberMask();

    /**
     * Model tests for BusinessRegistrationNumberMask
     */
    @Test
    public void testBusinessRegistrationNumberMask() {
        // TODO: test BusinessRegistrationNumberMask
    }

    /**
     * Test the property 'mask'
     */
    @Test
    public void maskTest() {
        // TODO: test mask
    }

    /**
     * Test the property 'ignoreWhitespace'
     */
    @Test
    public void ignoreWhitespaceTest() {
        // TODO: test ignoreWhitespace
    }

    /**
     * Test the property 'ignoreSpecialCharacter'
     */
    @Test
    public void ignoreSpecialCharacterTest() {
        // TODO: test ignoreSpecialCharacter
    }

    /**
     * Test the property 'prependZeroes'
     */
    @Test
    public void prependZeroesTest() {
        // TODO: test prependZeroes
    }

    /**
     * Test the property 'overwriteRepeating'
     */
    @Test
    public void overwriteRepeatingTest() {
        // TODO: test overwriteRepeating
    }

}
