/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.BusinessSearchRequestBusinessSearchModel;
import com.trulioo.normalizedapi.model.ServiceError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessSearchRequest
 */
public class BusinessSearchRequestTest {
    private final BusinessSearchRequest model = new BusinessSearchRequest();

    /**
     * Model tests for BusinessSearchRequest
     */
    @Test
    public void testBusinessSearchRequest() {
        // TODO: test BusinessSearchRequest
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'searchType'
     */
    @Test
    public void searchTypeTest() {
        // TODO: test searchType
    }

    /**
     * Test the property 'packageId'
     */
    @Test
    public void packageIdTest() {
        // TODO: test packageId
    }

    /**
     * Test the property 'callBackUrl'
     */
    @Test
    public void callBackUrlTest() {
        // TODO: test callBackUrl
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'consentForDataSources'
     */
    @Test
    public void consentForDataSourcesTest() {
        // TODO: test consentForDataSources
    }

    /**
     * Test the property 'business'
     */
    @Test
    public void businessTest() {
        // TODO: test business
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'requestErrors'
     */
    @Test
    public void requestErrorsTest() {
        // TODO: test requestErrors
    }

}
