/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.CommonRequiredFieldMetadata;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommonProviderCacheSchema
 */
public class CommonProviderCacheSchemaTest {
    private final CommonProviderCacheSchema model = new CommonProviderCacheSchema();

    /**
     * Model tests for CommonProviderCacheSchema
     */
    @Test
    public void testCommonProviderCacheSchema() {
        // TODO: test CommonProviderCacheSchema
    }

    /**
     * Test the property 'supportsCredentialValidation'
     */
    @Test
    public void supportsCredentialValidationTest() {
        // TODO: test supportsCredentialValidation
    }

    /**
     * Test the property 'requiredFieldMetadata'
     */
    @Test
    public void requiredFieldMetadataTest() {
        // TODO: test requiredFieldMetadata
    }

}
