/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Communication
 */
public class CommunicationTest {
    private final Communication model = new Communication();

    /**
     * Model tests for Communication
     */
    @Test
    public void testCommunication() {
        // TODO: test Communication
    }

    /**
     * Test the property 'mobileNumber'
     */
    @Test
    public void mobileNumberTest() {
        // TODO: test mobileNumber
    }

    /**
     * Test the property 'telephone'
     */
    @Test
    public void telephoneTest() {
        // TODO: test telephone
    }

    /**
     * Test the property 'telephone2'
     */
    @Test
    public void telephone2Test() {
        // TODO: test telephone2
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

}
