/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.Business;
import com.trulioo.normalizedapi.model.Communication;
import com.trulioo.normalizedapi.model.Document;
import com.trulioo.normalizedapi.model.DriverLicence;
import com.trulioo.normalizedapi.model.Location;
import com.trulioo.normalizedapi.model.NationalId;
import com.trulioo.normalizedapi.model.Passport;
import com.trulioo.normalizedapi.model.PersonInfo;
import com.trulioo.normalizedapi.model.RiskMonitorSettings;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataFields
 */
public class DataFieldsTest {
    private final DataFields model = new DataFields();

    /**
     * Model tests for DataFields
     */
    @Test
    public void testDataFields() {
        // TODO: test DataFields
    }

    /**
     * Test the property 'personInfo'
     */
    @Test
    public void personInfoTest() {
        // TODO: test personInfo
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'communication'
     */
    @Test
    public void communicationTest() {
        // TODO: test communication
    }

    /**
     * Test the property 'driverLicence'
     */
    @Test
    public void driverLicenceTest() {
        // TODO: test driverLicence
    }

    /**
     * Test the property 'nationalIds'
     */
    @Test
    public void nationalIdsTest() {
        // TODO: test nationalIds
    }

    /**
     * Test the property 'passport'
     */
    @Test
    public void passportTest() {
        // TODO: test passport
    }

    /**
     * Test the property 'document'
     */
    @Test
    public void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'business'
     */
    @Test
    public void businessTest() {
        // TODO: test business
    }

    /**
     * Test the property 'risk'
     */
    @Test
    public void riskTest() {
        // TODO: test risk
    }

    /**
     * Test the property 'countrySpecific'
     */
    @Test
    public void countrySpecificTest() {
        // TODO: test countrySpecific
    }

}
