/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataField
 */
public class DataFieldTest {
    private final DataField model = new DataField();

    /**
     * Model tests for DataField
     */
    @Test
    public void testDataField() {
        // TODO: test DataField
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    public void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'fieldGroup'
     */
    @Test
    public void fieldGroupTest() {
        // TODO: test fieldGroup
    }

}
