/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatasourceField
 */
public class DatasourceFieldTest {
    private final DatasourceField model = new DatasourceField();

    /**
     * Model tests for DatasourceField
     */
    @Test
    public void testDatasourceField() {
        // TODO: test DatasourceField
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    public void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'truMatchValue'
     */
    @Test
    public void truMatchValueTest() {
        // TODO: test truMatchValue
    }

    /**
     * Test the property 'truMatchThreshold'
     */
    @Test
    public void truMatchThresholdTest() {
        // TODO: test truMatchThreshold
    }

    /**
     * Test the property 'fieldGroup'
     */
    @Test
    public void fieldGroupTest() {
        // TODO: test fieldGroup
    }

}
