/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.AppendedField;
import com.trulioo.normalizedapi.model.DatasourceField;
import com.trulioo.normalizedapi.model.ServiceError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatasourceResult
 */
public class DatasourceResultTest {
    private final DatasourceResult model = new DatasourceResult();

    /**
     * Model tests for DatasourceResult
     */
    @Test
    public void testDatasourceResult() {
        // TODO: test DatasourceResult
    }

    /**
     * Test the property 'datasourceStatus'
     */
    @Test
    public void datasourceStatusTest() {
        // TODO: test datasourceStatus
    }

    /**
     * Test the property 'datasourceName'
     */
    @Test
    public void datasourceNameTest() {
        // TODO: test datasourceName
    }

    /**
     * Test the property 'datasourceFields'
     */
    @Test
    public void datasourceFieldsTest() {
        // TODO: test datasourceFields
    }

    /**
     * Test the property 'appendedFields'
     */
    @Test
    public void appendedFieldsTest() {
        // TODO: test appendedFields
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'fieldGroups'
     */
    @Test
    public void fieldGroupsTest() {
        // TODO: test fieldGroups
    }

}
