/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DemoPause
 */
public class DemoPauseTest {
    private final DemoPause model = new DemoPause();

    /**
     * Model tests for DemoPause
     */
    @Test
    public void testDemoPause() {
        // TODO: test DemoPause
    }

    /**
     * Test the property 'datasourceGroupName'
     */
    @Test
    public void datasourceGroupNameTest() {
        // TODO: test datasourceGroupName
    }

    /**
     * Test the property 'millisecondDelay'
     */
    @Test
    public void millisecondDelayTest() {
        // TODO: test millisecondDelay
    }

}
