/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Document
 */
public class DocumentTest {
    private final Document model = new Document();

    /**
     * Model tests for Document
     */
    @Test
    public void testDocument() {
        // TODO: test Document
    }

    /**
     * Test the property 'documentFrontImage'
     */
    @Test
    public void documentFrontImageTest() {
        // TODO: test documentFrontImage
    }

    /**
     * Test the property 'documentBackImage'
     */
    @Test
    public void documentBackImageTest() {
        // TODO: test documentBackImage
    }

    /**
     * Test the property 'livePhoto'
     */
    @Test
    public void livePhotoTest() {
        // TODO: test livePhoto
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    public void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'acceptIncompleteDocument'
     */
    @Test
    public void acceptIncompleteDocumentTest() {
        // TODO: test acceptIncompleteDocument
    }

    /**
     * Test the property 'validateDocumentImageQuality'
     */
    @Test
    public void validateDocumentImageQualityTest() {
        // TODO: test validateDocumentImageQuality
    }

}
