/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.LocationAdditionalFields;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Location
 */
public class LocationTest {
    private final Location model = new Location();

    /**
     * Model tests for Location
     */
    @Test
    public void testLocation() {
        // TODO: test Location
    }

    /**
     * Test the property 'buildingNumber'
     */
    @Test
    public void buildingNumberTest() {
        // TODO: test buildingNumber
    }

    /**
     * Test the property 'buildingName'
     */
    @Test
    public void buildingNameTest() {
        // TODO: test buildingName
    }

    /**
     * Test the property 'unitNumber'
     */
    @Test
    public void unitNumberTest() {
        // TODO: test unitNumber
    }

    /**
     * Test the property 'streetName'
     */
    @Test
    public void streetNameTest() {
        // TODO: test streetName
    }

    /**
     * Test the property 'streetType'
     */
    @Test
    public void streetTypeTest() {
        // TODO: test streetType
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'suburb'
     */
    @Test
    public void suburbTest() {
        // TODO: test suburb
    }

    /**
     * Test the property 'county'
     */
    @Test
    public void countyTest() {
        // TODO: test county
    }

    /**
     * Test the property 'stateProvinceCode'
     */
    @Test
    public void stateProvinceCodeTest() {
        // TODO: test stateProvinceCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'poBox'
     */
    @Test
    public void poBoxTest() {
        // TODO: test poBox
    }

    /**
     * Test the property 'additionalFields'
     */
    @Test
    public void additionalFieldsTest() {
        // TODO: test additionalFields
    }

}
