/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NationalId
 */
public class NationalIdTest {
    private final NationalId model = new NationalId();

    /**
     * Model tests for NationalId
     */
    @Test
    public void testNationalId() {
        // TODO: test NationalId
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'districtOfIssue'
     */
    @Test
    public void districtOfIssueTest() {
        // TODO: test districtOfIssue
    }

    /**
     * Test the property 'cityOfIssue'
     */
    @Test
    public void cityOfIssueTest() {
        // TODO: test cityOfIssue
    }

    /**
     * Test the property 'provinceOfIssue'
     */
    @Test
    public void provinceOfIssueTest() {
        // TODO: test provinceOfIssue
    }

    /**
     * Test the property 'countyOfIssue'
     */
    @Test
    public void countyOfIssueTest() {
        // TODO: test countyOfIssue
    }

}
