/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Passport
 */
public class PassportTest {
    private final Passport model = new Passport();

    /**
     * Model tests for Passport
     */
    @Test
    public void testPassport() {
        // TODO: test Passport
    }

    /**
     * Test the property 'mrz1'
     */
    @Test
    public void mrz1Test() {
        // TODO: test mrz1
    }

    /**
     * Test the property 'mrz2'
     */
    @Test
    public void mrz2Test() {
        // TODO: test mrz2
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'dayOfExpiry'
     */
    @Test
    public void dayOfExpiryTest() {
        // TODO: test dayOfExpiry
    }

    /**
     * Test the property 'monthOfExpiry'
     */
    @Test
    public void monthOfExpiryTest() {
        // TODO: test monthOfExpiry
    }

    /**
     * Test the property 'yearOfExpiry'
     */
    @Test
    public void yearOfExpiryTest() {
        // TODO: test yearOfExpiry
    }

}
