/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.PersonInfoAdditionalFields;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonInfo
 */
public class PersonInfoTest {
    private final PersonInfo model = new PersonInfo();

    /**
     * Model tests for PersonInfo
     */
    @Test
    public void testPersonInfo() {
        // TODO: test PersonInfo
    }

    /**
     * Test the property 'firstGivenName'
     */
    @Test
    public void firstGivenNameTest() {
        // TODO: test firstGivenName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'firstSurName'
     */
    @Test
    public void firstSurNameTest() {
        // TODO: test firstSurName
    }

    /**
     * Test the property 'secondSurname'
     */
    @Test
    public void secondSurnameTest() {
        // TODO: test secondSurname
    }

    /**
     * Test the property 'isoLatin1Name'
     */
    @Test
    public void isoLatin1NameTest() {
        // TODO: test isoLatin1Name
    }

    /**
     * Test the property 'dayOfBirth'
     */
    @Test
    public void dayOfBirthTest() {
        // TODO: test dayOfBirth
    }

    /**
     * Test the property 'monthOfBirth'
     */
    @Test
    public void monthOfBirthTest() {
        // TODO: test monthOfBirth
    }

    /**
     * Test the property 'yearOfBirth'
     */
    @Test
    public void yearOfBirthTest() {
        // TODO: test yearOfBirth
    }

    /**
     * Test the property 'minimumAge'
     */
    @Test
    public void minimumAgeTest() {
        // TODO: test minimumAge
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'additionalFields'
     */
    @Test
    public void additionalFieldsTest() {
        // TODO: test additionalFields
    }

}
