/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonOfSignificantControl
 */
public class PersonOfSignificantControlTest {
    private final PersonOfSignificantControl model = new PersonOfSignificantControl();

    /**
     * Model tests for PersonOfSignificantControl
     */
    @Test
    public void testPersonOfSignificantControl() {
        // TODO: test PersonOfSignificantControl
    }

    /**
     * Test the property 'firstGivenName'
     */
    @Test
    public void firstGivenNameTest() {
        // TODO: test firstGivenName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'firstSurname'
     */
    @Test
    public void firstSurnameTest() {
        // TODO: test firstSurname
    }

    /**
     * Test the property 'secondSurname'
     */
    @Test
    public void secondSurnameTest() {
        // TODO: test secondSurname
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'yearOfBirth'
     */
    @Test
    public void yearOfBirthTest() {
        // TODO: test yearOfBirth
    }

    /**
     * Test the property 'monthOfBirth'
     */
    @Test
    public void monthOfBirthTest() {
        // TODO: test monthOfBirth
    }

    /**
     * Test the property 'dayOfBirth'
     */
    @Test
    public void dayOfBirthTest() {
        // TODO: test dayOfBirth
    }

}
