/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.DatasourceResult;
import com.trulioo.normalizedapi.model.RecordRule;
import com.trulioo.normalizedapi.model.ServiceError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Record
 */
public class RecordTest {
    private final Record model = new Record();

    /**
     * Model tests for Record
     */
    @Test
    public void testRecord() {
        // TODO: test Record
    }

    /**
     * Test the property 'transactionRecordID'
     */
    @Test
    public void transactionRecordIDTest() {
        // TODO: test transactionRecordID
    }

    /**
     * Test the property 'recordStatus'
     */
    @Test
    public void recordStatusTest() {
        // TODO: test recordStatus
    }

    /**
     * Test the property 'secondaryRecordStatus'
     */
    @Test
    public void secondaryRecordStatusTest() {
        // TODO: test secondaryRecordStatus
    }

    /**
     * Test the property 'datasourceResults'
     */
    @Test
    public void datasourceResultsTest() {
        // TODO: test datasourceResults
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'rule'
     */
    @Test
    public void ruleTest() {
        // TODO: test rule
    }

}
