/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RecordRule
 */
public class RecordRuleTest {
    private final RecordRule model = new RecordRule();

    /**
     * Model tests for RecordRule
     */
    @Test
    public void testRecordRule() {
        // TODO: test RecordRule
    }

    /**
     * Test the property 'ruleName'
     */
    @Test
    public void ruleNameTest() {
        // TODO: test ruleName
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'secondaryRuleName'
     */
    @Test
    public void secondaryRuleNameTest() {
        // TODO: test secondaryRuleName
    }

    /**
     * Test the property 'secondaryRuleNote'
     */
    @Test
    public void secondaryRuleNoteTest() {
        // TODO: test secondaryRuleNote
    }

}
