/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.Address;
import com.trulioo.normalizedapi.model.BusinessSearchResponseIndustryCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Result
 */
public class ResultTest {
    private final Result model = new Result();

    /**
     * Model tests for Result
     */
    @Test
    public void testResult() {
        // TODO: test Result
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'matchingScore'
     */
    @Test
    public void matchingScoreTest() {
        // TODO: test matchingScore
    }

    /**
     * Test the property 'businessRegistrationNumber'
     */
    @Test
    public void businessRegistrationNumberTest() {
        // TODO: test businessRegistrationNumber
    }

    /**
     * Test the property 'dunsNumber'
     */
    @Test
    public void dunsNumberTest() {
        // TODO: test dunsNumber
    }

    /**
     * Test the property 'businessTaxIDNumber'
     */
    @Test
    public void businessTaxIDNumberTest() {
        // TODO: test businessTaxIDNumber
    }

    /**
     * Test the property 'businessLicenseNumber'
     */
    @Test
    public void businessLicenseNumberTest() {
        // TODO: test businessLicenseNumber
    }

    /**
     * Test the property 'jurisdictionOfIncorporation'
     */
    @Test
    public void jurisdictionOfIncorporationTest() {
        // TODO: test jurisdictionOfIncorporation
    }

    /**
     * Test the property 'fullAddress'
     */
    @Test
    public void fullAddressTest() {
        // TODO: test fullAddress
    }

    /**
     * Test the property 'businessStatus'
     */
    @Test
    public void businessStatusTest() {
        // TODO: test businessStatus
    }

    /**
     * Test the property 'originalBusinessStatus'
     */
    @Test
    public void originalBusinessStatusTest() {
        // TODO: test originalBusinessStatus
    }

    /**
     * Test the property 'tradeStyleName'
     */
    @Test
    public void tradeStyleNameTest() {
        // TODO: test tradeStyleName
    }

    /**
     * Test the property 'businessType'
     */
    @Test
    public void businessTypeTest() {
        // TODO: test businessType
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'otherBusinessNames'
     */
    @Test
    public void otherBusinessNamesTest() {
        // TODO: test otherBusinessNames
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'telephone'
     */
    @Test
    public void telephoneTest() {
        // TODO: test telephone
    }

    /**
     * Test the property 'taxIDNumber'
     */
    @Test
    public void taxIDNumberTest() {
        // TODO: test taxIDNumber
    }

    /**
     * Test the property 'taxIDNumbers'
     */
    @Test
    public void taxIDNumbersTest() {
        // TODO: test taxIDNumbers
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'webDomain'
     */
    @Test
    public void webDomainTest() {
        // TODO: test webDomain
    }

    /**
     * Test the property 'webDomains'
     */
    @Test
    public void webDomainsTest() {
        // TODO: test webDomains
    }

    /**
     * Test the property 'naics'
     */
    @Test
    public void naicsTest() {
        // TODO: test naics
    }

    /**
     * Test the property 'sic'
     */
    @Test
    public void sicTest() {
        // TODO: test sic
    }

}
