/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionStatus
 */
public class TransactionStatusTest {
    private final TransactionStatus model = new TransactionStatus();

    /**
     * Model tests for TransactionStatus
     */
    @Test
    public void testTransactionStatus() {
        // TODO: test TransactionStatus
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'transactionRecordId'
     */
    @Test
    public void transactionRecordIdTest() {
        // TODO: test transactionRecordId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'uploadedDt'
     */
    @Test
    public void uploadedDtTest() {
        // TODO: test uploadedDt
    }

    /**
     * Test the property 'isTimedOut'
     */
    @Test
    public void isTimedOutTest() {
        // TODO: test isTimedOut
    }

}
