/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerifyAddressCredentials
 */
public class VerifyAddressCredentialsTest {
    private final VerifyAddressCredentials model = new VerifyAddressCredentials();

    /**
     * Model tests for VerifyAddressCredentials
     */
    @Test
    public void testVerifyAddressCredentials() {
        // TODO: test VerifyAddressCredentials
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'username2'
     */
    @Test
    public void username2Test() {
        // TODO: test username2
    }

    /**
     * Test the property 'password2'
     */
    @Test
    public void password2Test() {
        // TODO: test password2
    }

    /**
     * Test the property 'username3'
     */
    @Test
    public void username3Test() {
        // TODO: test username3
    }

    /**
     * Test the property 'password3'
     */
    @Test
    public void password3Test() {
        // TODO: test password3
    }

    /**
     * Test the property 'username4'
     */
    @Test
    public void username4Test() {
        // TODO: test username4
    }

    /**
     * Test the property 'password4'
     */
    @Test
    public void password4Test() {
        // TODO: test password4
    }

}
