/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.DataFields;
import com.trulioo.normalizedapi.model.VerifyAddressCredentials;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerifyAddressRequest
 */
public class VerifyAddressRequestTest {
    private final VerifyAddressRequest model = new VerifyAddressRequest();

    /**
     * Model tests for VerifyAddressRequest
     */
    @Test
    public void testVerifyAddressRequest() {
        // TODO: test VerifyAddressRequest
    }

    /**
     * Test the property 'verificationType'
     */
    @Test
    public void verificationTypeTest() {
        // TODO: test verificationType
    }

    /**
     * Test the property 'packageId'
     */
    @Test
    public void packageIdTest() {
        // TODO: test packageId
    }

    /**
     * Test the property 'callBackUrl'
     */
    @Test
    public void callBackUrlTest() {
        // TODO: test callBackUrl
    }

    /**
     * Test the property 'cleansedAddress'
     */
    @Test
    public void cleansedAddressTest() {
        // TODO: test cleansedAddress
    }

    /**
     * Test the property 'consentForDataSources'
     */
    @Test
    public void consentForDataSourcesTest() {
        // TODO: test consentForDataSources
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'customerReferenceID'
     */
    @Test
    public void customerReferenceIDTest() {
        // TODO: test customerReferenceID
    }

    /**
     * Test the property 'dataFields'
     */
    @Test
    public void dataFieldsTest() {
        // TODO: test dataFields
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'providerCredentials'
     */
    @Test
    public void providerCredentialsTest() {
        // TODO: test providerCredentials
    }

}
