/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.Record;
import com.trulioo.normalizedapi.model.ServiceError;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerifyResult
 */
public class VerifyResultTest {
    private final VerifyResult model = new VerifyResult();

    /**
     * Model tests for VerifyResult
     */
    @Test
    public void testVerifyResult() {
        // TODO: test VerifyResult
    }

    /**
     * Test the property 'transactionID'
     */
    @Test
    public void transactionIDTest() {
        // TODO: test transactionID
    }

    /**
     * Test the property 'uploadedDt'
     */
    @Test
    public void uploadedDtTest() {
        // TODO: test uploadedDt
    }

    /**
     * Test the property 'completedDt'
     */
    @Test
    public void completedDtTest() {
        // TODO: test completedDt
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'record'
     */
    @Test
    public void recordTest() {
        // TODO: test record
    }

    /**
     * Test the property 'customerReferenceID'
     */
    @Test
    public void customerReferenceIDTest() {
        // TODO: test customerReferenceID
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
