/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trulioo.normalizedapi.model.DataFields;
import com.trulioo.normalizedapi.model.ServiceError;
import com.trulioo.normalizedapi.model.VerifyRequestMetadata;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerifyRequest
 */
public class VerifyRequestTest {
    private final VerifyRequest model = new VerifyRequest();

    /**
     * Model tests for VerifyRequest
     */
    @Test
    public void testVerifyRequest() {
        // TODO: test VerifyRequest
    }

    /**
     * Test the property 'verificationType'
     */
    @Test
    public void verificationTypeTest() {
        // TODO: test verificationType
    }

    /**
     * Test the property 'packageId'
     */
    @Test
    public void packageIdTest() {
        // TODO: test packageId
    }

    /**
     * Test the property 'callBackUrl'
     */
    @Test
    public void callBackUrlTest() {
        // TODO: test callBackUrl
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'cleansedAddress'
     */
    @Test
    public void cleansedAddressTest() {
        // TODO: test cleansedAddress
    }

    /**
     * Test the property 'consentForDataSources'
     */
    @Test
    public void consentForDataSourcesTest() {
        // TODO: test consentForDataSources
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'customerReferenceID'
     */
    @Test
    public void customerReferenceIDTest() {
        // TODO: test customerReferenceID
    }

    /**
     * Test the property 'dataFields'
     */
    @Test
    public void dataFieldsTest() {
        // TODO: test dataFields
    }

    /**
     * Test the property 'requestErrors'
     */
    @Test
    public void requestErrorsTest() {
        // TODO: test requestErrors
    }

    /**
     * Test the property 'verboseMode'
     */
    @Test
    public void verboseModeTest() {
        // TODO: test verboseMode
    }

    /**
     * Test the property 'requestMetadata'
     */
    @Test
    public void requestMetadataTest() {
        // TODO: test requestMetadata
    }

}
