/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.trulioo.normalizedapi.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-18T08:58:06.298535900-07:00[America/Los_Angeles]")
public class DemoPause {
  public static final String SERIALIZED_NAME_DATASOURCE_GROUP_NAME = "DatasourceGroupName";
  @SerializedName(SERIALIZED_NAME_DATASOURCE_GROUP_NAME)
  private String datasourceGroupName;

  public static final String SERIALIZED_NAME_MILLISECOND_DELAY = "MillisecondDelay";
  @SerializedName(SERIALIZED_NAME_MILLISECOND_DELAY)
  private Integer millisecondDelay;

  public DemoPause() {
  }

  public DemoPause datasourceGroupName(String datasourceGroupName) {
    
    this.datasourceGroupName = datasourceGroupName;
    return this;
  }

   /**
   * 
   * @return datasourceGroupName
  **/
  @javax.annotation.Nullable

  public String getDatasourceGroupName() {
    return datasourceGroupName;
  }


  public void setDatasourceGroupName(String datasourceGroupName) {
    this.datasourceGroupName = datasourceGroupName;
  }


  public DemoPause millisecondDelay(Integer millisecondDelay) {
    
    this.millisecondDelay = millisecondDelay;
    return this;
  }

   /**
   * 
   * @return millisecondDelay
  **/
  @javax.annotation.Nullable

  public Integer getMillisecondDelay() {
    return millisecondDelay;
  }


  public void setMillisecondDelay(Integer millisecondDelay) {
    this.millisecondDelay = millisecondDelay;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemoPause demoPause = (DemoPause) o;
    return Objects.equals(this.datasourceGroupName, demoPause.datasourceGroupName) &&
        Objects.equals(this.millisecondDelay, demoPause.millisecondDelay);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasourceGroupName, millisecondDelay);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemoPause {\n");
    sb.append("    datasourceGroupName: ").append(toIndentedString(datasourceGroupName)).append("\n");
    sb.append("    millisecondDelay: ").append(toIndentedString(millisecondDelay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DatasourceGroupName");
    openapiFields.add("MillisecondDelay");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DemoPause
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DemoPause.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DemoPause is not found in the empty JSON string", DemoPause.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DemoPause.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DemoPause` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("DatasourceGroupName") != null && !jsonObj.get("DatasourceGroupName").isJsonNull()) && !jsonObj.get("DatasourceGroupName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DatasourceGroupName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DatasourceGroupName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DemoPause.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DemoPause' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DemoPause> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DemoPause.class));

       return (TypeAdapter<T>) new TypeAdapter<DemoPause>() {
           @Override
           public void write(JsonWriter out, DemoPause value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DemoPause read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DemoPause given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DemoPause
  * @throws IOException if the JSON string is invalid with respect to DemoPause
  */
  public static DemoPause fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DemoPause.class);
  }

 /**
  * Convert an instance of DemoPause to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

