/*
 * NAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trulioo.normalizedapi.api;

import com.trulioo.normalizedapi.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectionApi
 */
@Disabled
public class ConnectionApiTest {

    private final ConnectionApi api = new ConnectionApi();

    /**
     * SayHello
     *
     * This method enables you to check if your system can connect to our system. You can even use a web browser to verify a connection to our system.  Applied a maximum length for the name parameter of 100 via a route constraint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sayHelloTest() throws ApiException {
        String name = null;
        Object response = api.sayHello(name);
        // TODO: test validations
    }

    /**
     * TestAuthentication
     *
     * This method enables you to check if your credentials are valid. You will need to provide a valid token to ensure a successful response.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void testAuthenticationTest() throws ApiException {
        String response = api.testAuthentication();
        // TODO: test validations
    }

}
